services:
  db:
    image: postgres:16.6-bullseye
    container_name: "checkbox-db"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - ".env"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s

  app:
    build:
      context: .
    container_name: "checkbox-app"
    ports:
      - "${HOST_PORT}:80"
    post_start:
      - command: alembic upgrade head
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - ".env"
    networks:
      - backend
    restart: on-failure:10

networks:
  backend:

volumes:
  db-data: 
